### ISSUE TITLE
[Bug]: Broken all/nullable handling

### ISSUE THREAD

**Issue by bkoelman** [domaindrivendev/Swashbuckle.AspNetCore#3683]
### Describe the bug

The merge of #3680 is very breaking. For example, it changes the OAS 3.0 component schema structure from:
```json
"links": {
  "allOf": [
    {
      "$ref": "#/components/schemas/error-links"
    }
  ],
  "nullable": true
}
```
to:
```json
"links": {
  "oneOf": [
    {
      "$ref": "#/components/schemas/error-links"
    },
    {
      "nullable": true
    }
  ]
}
```
It looks like the v10.0.2 release containing this change was retracted, but we build/test against the MyGet feed, which still contains this change. As a result, lots of our tests that assert on the output OAS structure are currently broken. Ignoring that, generating a C# client using Kiota against the changed files results in code that doesn't compile. Can the commit be reverted in the main branch as well?

**Comment by martincostello** [comment]
D'oh, I remember now I meant to check this for 3.0 but forgot.

Luckily the NuGet API key had expired so the release never went out.

I won't be reverting it as there's basically just me doing releases anyway, so it'll just be fix forward as I know not to release 10.0.2 until this is sorted.

**Comment by bkoelman** [comment]
As far as I'm aware, the original OAS 3.0 structure is correct. Because title/description/nullable can't be combined with a $ref, the common workaround is to wrap the $ref in an allOf. Swashbuckle provides the `UseAllOfToExtendReferenceSchemas()` method to do that automatically.

For OAS 3.1, the story is different. The allOf workaround is no longer needed (but still allowed). Then my example from above can be reduced to:
```json
"links": {
  "type": "null",
  "allOf": [
    {
      "$ref": "#/components/schemas/error-links"
    }
  ]
}
```
And that works with both NSwag and kiota. What _may_ look even better is to use: `"type": ["null", "object"]`. Unfortunately, doing that breaks the entire ecosystem. It was initially tried in Microsoft.OpenAPI, but reverted later.

Aside from the above, there are two _additional_ legal syntaxes to express the combination of nullable and something else. See https://github.com/OAI/OpenAPI-Specification/issues/3148 for details. Because OAS 3.1 is hardly supported by client generators, it's hard to pick one. 

I found that [openapigenerator](https://github.com/OpenAPITools/openapi-generator) currently only supports the following style in OAS 3.1:
```yaml
RelationshipToOne:
  type: object
  properties:
    data:
      anyOf:
       - type: 'null'
       - $ref: "#/components/schemas/Relationship"
```
Kiota also supports OAS 3.1, but I don't know what it accepts. NSwag does not support OAS 3.1 at all.

**Comment by bkoelman** [comment]
The reason I'd like the change reverted (or at least the part that breaks the structure) is that the chosen solution is fundamentally flawed, and there's no obvious correct alternative.

In the original issue #3649, the user wants an OAS 3.1 document, but also calls `options.UseAllOfToExtendReferenceSchemas();`, which is a workaround for a limitation in OAS 3.0. Why do that in the first place? The simplest solution seems to be not to call that method.

But if a user wants to serve both OAS 3.0 and 3.1 via different endpoints, the current `UseAllOfToExtendReferenceSchemas` becomes insufficient. A possible solution is to make Swashbuckle auto-ignore `options.UseAllOfToExtendReferenceSchemas()` when emitting OAS 3.1, effectively making the schema generator version-aware (a breaking change).

So there are basically three valid syntaxes in OAS 3.1 to represent the OAS 3.0 equivalent of a nullable $ref. Before Swashbuckle settles on an output structure, I recommend investigating which structures are actually working properly in popular documentation tools (SwaggerUI, Redoc, Scalar) and code generators (NSwag, kiota, openapigenerator). And possibly offer multiple ways via settings. But the difficulty with settings is that API developers may not know what tools OAS consumers are going to use. A better solution would be if the OAS consumer could pass a query string parameter to choose a style.

This is a hard problem.

**Comment by bkoelman** [comment]
Specifically to enums, the recommended structure in OAS 3.1 is quite different too, see https://stackoverflow.com/questions/66465888/how-to-define-enum-mapping-in-openapi. To support descriptions on enum members in OAS 3.0, multiple extensions exist (which are incompatible with each other).

**Comment by martincostello** [comment]
> generating a C# client using Kiota against the changed files results in code that doesn't compile

Could you provide some more details (and ideally a repro) for that please?

I've been trying to work on some integration tests today that validate whether OpenAPI clients generated from the OpenAPI documents can be produced and that they compile, but the compilations are succeeding (including with a local change to have the test site for the change to produce a 3.0 document instead of 3.1).

I guess there's a bit more nuance to the problem you're seeing in how it interacts with some other documents that causes the invalid code to be generated.

**Comment by bkoelman** [comment]
> > generating a C# client using Kiota against the changed files results in code that doesn't compile
> 
> Could you provide some more details (and ideally a repro) for that please?

Sure, but could you please first restore the master branch to a working state again? We're totally broken by this (all Dependabot updates fail). There's little point in offering a dev feed when that's not supposed to contain a working snapshot, right?

> I've been trying to work on some integration tests today that validate whether OpenAPI clients generated from the OpenAPI documents can be produced and that they compile, but the compilations are succeeding (including with a local change to have the test site for the change to produce a 3.0 document instead of 3.1).

Yes, I've seen that. Unfortunately, that doesn't prove much. Upon further inspection, aside from non-compiling code, the C# API surface that Kiota generates becomes _very_ different. Somehow, it interprets the change as OAS inheritance (new classes are added, including logic for discriminators, existing classes are deleted, the types of model properties have changed, etc). So even if the code would compile, it would still be a breaking change. Creating tests to reliably guard against this takes quite a bit of effort. Easiest would be to assert the generated C# code hasn't changed, but that's brittle because it implicitly takes a dependency on generator internals, which change over time. The only thing that ultimately matters is that the generated client still functions like it did (in terms of producing the right HTTP request (URL, headers, query strings), and serialization). What we found works best is the following:
1. An xUnit project that references Swashbuckle, where each directory contains:
   - A set of models to represent a scenario. For example: nullable/non-nullable properties, inheritance, documentation, headers and query string handling, or something else
   - Shared startup code that configures an in-memory app via TestServer, setting up dependencies, Swashbuckle, HTTP endpoints, etc.
   - Tests that assert on (fragments of) the OAS structure by first downloading it. When such a test runs, it also writes the OAS file to disk (we need that later). If the OAS file changed for some reason, it introduces pending changes that are easy to spot and review.
2. An xUnit project that references the OAS files on disk (from the previous step), generating C# clients per scenario directory at compile time. Each scenario then contains a set of tests that use the shared startup code, invoke a generated method that sends an HTTP request (via TestServer), and then assert on the response.

For example, the first project contains models and startup code:
```c#
public abstract class Channel
{
    public long Id { get; set; }
    public string? Name { get; set; }
    public bool? IsCommercial { get; set; }
}

public class ReadOnlyChannel : Channel;

public class TestStartup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddSwaggerGen();
    }
    public void Configure(IApplicationBuilder app)
    {
        app.MapGet(....); // Operation ID: GetReadOnlyChannel
        app.UseSwagger();
    }
}
```
Along with tests that assert on OAS fragments:
```c#
[Fact]
public async Task Component_schemas_are_exposed()
{
    // Act
    JsonElement document = await _testContext.GetSwaggerDocumentAsync();

    // Assert
    document.Should().ContainPath("components.schemas").With(schemasElement =>
    {
        schemasElement.Should().ContainPath("Channel").Should().BeJson("""
            ...
            """);

        schemasElement.Should().ContainPath("ReadOnlyChannel").Should().BeJson("""
            ...
            """);
    });
}
```

And the second project invokes a request via the generated client (using NSwag in this case):
```c#
[Fact]
public async Task Can_get_primary_resource_by_ID()
{
    // Arrange
    ReadOnlyChannel channel = _fakers.ReadOnlyChannel.GenerateOne();

    await _testContext.RunOnDatabaseAsync(async dbContext =>
    {
        dbContext.ReadOnlyChannels.Add(channel);
        await dbContext.SaveChangesAsync();
    });

    using HttpClient httpClient = _testContext.Factory.CreateDefaultClient(_logHttpMessageHandler);
    var apiClient = new RestrictedControllersClient(httpClient); // <-- generated client

    // Act
    PrimaryReadOnlyChannelResponseDocument response = await apiClient.GetReadOnlyChannelAsync(channel.Id);

    // Assert
    response.Should().NotBeNull();
    response.Id.Should().Be(channel.Id);
    response.Name.Should().Be(channel.Name);
    response.IsCommercial.Should().Be(channel.IsCommercial);
}
```

Note: the code above is based on actual tests that I simplified by hand, so it may contain mistakes. The point is to explain the general mechanism.

Using this approach, we currently have 7000+ tests that assert on the OAS structure our project generates (we have extended Swashbuckle pretty extreme). The NSwag/Kiota tests (180 each) represent key features that are relevant to our project, but don't cover everything possible in OAS. We'd like to add tests for more generators in the future.

**Comment by martincostello** [comment]
Having some tests that actually use client to interact with a functional service and checks it works is a good idea, I hadn't considered that. I'll look into doing something like that in the future as an extension of the idea.

However, I would still like to create a concrete test that fails due to the bug introduced first before any remedial work. I want to surface the break, then I can "TDD" the default branch back to a working state. The fact it's broken yet there's a green CI is more important to resolve first than just reverting the commit that introduced it.

There was a snapshot test created before the change was made, but the delta to it after it was "expected", so the change to the snapshot was committed too. No other snapshots changed, which point to a lack of coverage, which is what I want to address first. Had some other snapshots changed or something else failed that would have been a hint that maybe the change was wrong in the first place.

I understand that the default branch is currently broken, but it's a prerelease feed - it's shouldn't be unexpected that there is a risk it might contain bugs.

If these bugs are being caught by your CI at PR time and not being merged and deployed, then there shouldn't be any urgency for you getting changes from the default branch here, as excluding changes to test dependencies, the only change you don't have is the one with the bug in it, so you're not missing out on anything.

It was pure luck that the key expired that meant this didn't get released as stable, but even if it had, the situation would be the same. 10.0.2 would just be "bad" and the recommendation would have been to roll back to 10.0.1 while I did the exact same process for fix things up for a 10.0.3.

A pure rollback is a last resort I'm keeping for if there's a future change that _has_ to be released before appropriate tests and a proper fix can be made, but right now there's moot as I can't release _anything_ to NuGet as I'm waiting on the package owner to set up Trusted Publishing (or regenerate the API key).

**Comment by martincostello** [comment]
It's also worth noting, that the built-in validation in OpenAPI.NET is run against all the OpenAPI documents generated in the snapshot tests, and they don't highlight any issues with the change either.

That's to say that there's lots of attempts to validate the documents make sense here automagically, and this change _still_ fell through the cracks.

**Comment by bkoelman** [comment]
Let's zoom out a bit to gain some perspective.

The fundamental problem with the OpenAPI spec is that it's derived from JSON schema, which is a constraints-based language. An empty JSON schema means: "allow anything". OpenAPI, on the other hand, tries to define the opposite: which constructs are allowed. This conceptual mismatch leads to many questions that the spec doesn't answer. It is highly convention-based, so consumers try to detect conventions in order to produce object models. Furthermore, the OpenAPI spec is ambiguous in many ways, leading to implementations making their own choices. This is why end-to-end scenarios are often broken (especially with v3.1, which is still pretty young). While the spec is a good starting point for an implementation, whether a construct actually works highly depends on both the producing and consuming systems. In practice, it's a matter of trying out different combinations to see which OAS structure works best before deciding which to produce. As a result, simply implementing the spec alone is insufficient if the goal is to create a library users can actually use.

OpenAPI.NET is an object model serializer. While it includes a few basic validations, it's pretty easy to make it produce a semantically invalid OpenAPI document. Or a document that any consuming system would choke on. This is unavoidable because this library has no understanding of the broader context. For example, it has no opinion on how to implement inheritance, which can be done in multiple ways (allOf, oneOf, with/without discriminator), so it simply exposes the language constructs. It doesn't purge unused component schemas, it doesn't unwrap redundant multiple nested `allOf`s, and many more. This means that when validation fails, you're doing something wrong. If it succeeds, it doesn't mean much. Also, beware that its writer sometimes just ignores elements in the tree without producing a validation error. For example, when combining a `$ref` with `nullable` in 3.0, it simply doesn't write the `nullable` because the spec forbids that. It doesn't auto-wrap in an `allOf` for you, despite the spec requiring that. It has no preference on how enums are defined. For OpenAPI 3.1, the project was updated to write the structure dictated by the spec, nothing more. The project is mostly abandoned; the Kiota developers just patched it up a little to enable reading/writing syntactically valid OAS 3.1 documents.

Swashbuckle, NSwag, and openapigenerator are established, feature-rich, mature, and highly configurable/extendable libraries suitable for advanced use. Unfortunately, both NSwag and Swashbuckle lack fundamental test coverage. This is why NSwag is extremely conservative in taking changes; it has become impossible to oversee their implications. I don't expect it to support OAS 3.1 in the near future, because it relies on NJsonSchema.

ASP.NET OpenAPI and Kiota are newcomers that work for simple cases. They offer limited extensibility, break often and are not a suitable alternative for advanced solutions anytime soon.

Swashbuckle was unmaintained for a while, but fortunately, that's no longer the case. It does, though, suffer from the problem that contributors lack the deep understanding of OpenAPI that the original author has. TDD is nice, but not a replacement for rethinking the architectural changes needed to properly support OpenAPI 3.1. Did you know, for example, that the `byte`/`binary`/`base64` formats [must not be used](https://github.com/OAI/OpenAPI-Specification/releases/tag/3.1.0-rc0) in OpenAPI 3.1? I consider the current support for 3.1 in Swashbuckle experimental at best, which is why I haven't written any tests for it yet.

To add _usable_ support for OpenAPI 3.1 to Swashbuckle, the logical course of action is to first add test coverage for core existing features (as in my example) using OAS 3.0 to ensure it won't break. Then design alternate schema constructs for OpenAPI 3.1, which requires the schema generator to become version-aware. I suspect breaking changes in various places will be needed, so it may become the next major version. This is a process that likely takes months, which is why I'd like to see the silly "fix" reverted short-term. I'm testing against the dev-feed exactly for this reason: to catch mistakes due to lack of experience like that early, so our users don't have to suffer from them. Basically, our comprehensive test suite enables what Swashbuckle itself should cover. In a sense, we have your back, but now you're telling me to stop doing that? We trusted on released versions in the past, but that didn't work so well. The Swashbuckle build is green because it lacks fundamental test coverage. Efforts should focus on solving that before taking any non-trivial PRs that affect the generated OAS.

**Comment by martincostello** [comment]
We agree that coverage is lacking. That's what I want to tackle first.

Please share an example I can use that proves _with code_ that the changes in the PR are broken, and then I can try to move things to a stable state from there, even if it does end up amounting to effectively being a revert.

But I want a test that proves it's broken first, that's more useful than a knee-jerk revert that just swaps one issue for another (what it was trying to fix). Otherwise it just feels a bit like sweeping the problem under the carpet, and means other changes in the space might just break more things.

Using the prerelease versions _for testing_ is great, and that's found this issue, which is also very useful. However, it's not intended/supported for use in production. That's at your own risk. It's also easy to work around - rollback to the last-known-good version that worked for you, and then await a PR with a new (pre)version that works again.

I'd rather prioritise testing to find the problem you're reporting first than "just revert".

I also didn't know about any of the things you've noted that 3.1 shouldn't do that it apparently currently does here. It's a shame those things weren't known about before I released v10, then maybe I would have held it back and looked into fixing those things first.

It's the weekend anyway, so movement in either direction will be limited.

**Comment by bkoelman** [comment]
Here are the steps to reproduce:
1. Clone https://github.com/json-api-dotnet/JsonApiDotNetCore
1. Ensure Docker Desktop is installed and running
1. `docker run --pull always --rm --detach --name jsonapi-postgresql-db -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 postgres:latest -N 500`
1. `dotnet tool restore`
1. `dotnet restore`
1. Open `JsonApiDotNetCore.sln` in VS 2026, Build solution
1. In Test Explorer, run all tests in project `OpenApiTests (net10.0)`; a bunch of tests fail (ignore this for now)
1. Switch to Git Changes view and observe changes for various `swagger.g.json` files
1. Build project `test/OpenApiKiotaEndToEndTests`
1. Observe errors in the Error List window about `IBackedModel`
1. Switch to Git Changes view and observe lots of changes in `*\GeneratedCode` directories (bunch of new kiota code added)

To revert back to a working state:
1. Open `Solution Items/package-versions.props`, change `SwashbuckleVersion` (not to be confused with `SwashbuckleFrozenVersion`) to `10.0.1` and save
1. Rebuild solution and re-run `OpenApiTests (net10.0)`
1. Build solution, which succeeds without errors now (and pending changes have disappeared)
1. Run all tests in the solution; they should all be green now

Note that the schema diffs after applying the repro steps are pretty small. This is because we use custom schema generators for most of the components in documents. `ErrorObject` is one of the few exceptions we defer to the Swashbuckle generator without interception.

**Comment by martincostello** [comment]
Thanks for the repro.

Looks the bug here is triggering a bug in Kiota, which is why the compilation is initially failing. Assuming I've understood things correctly, Kiota is emitting code for `IBackedModel` when `"usesBackingStore": true`, but isn't emitting the `using Microsoft.Kiota.Abstractions.Store;` to go with it.

If I then add `<Using Include="Microsoft.Kiota.Abstractions.Store" />`, then that breaks the handling for a nullable enum, which then causes your tests to fail to compile.

Hopefully I should be able to easily extend the test project I've added for some E2E validation to include that, which should then break stuff.

**Comment by bkoelman** [comment]
> I assumed from the description that the OpenAPI document was causing Kiota to generate non-sensical C# to descript the API client but that's not the case.

That's incorrect. Kiota _does_ generate broken code. Yes, it compiles after adding the `using`, but it changes how data is (de)serialized, no longer matching what the API expects. For example, the following property is missing now:

<img width="403" height="73" alt="Image" src="https://github.com/user-attachments/assets/6335c683-742a-4404-9ecf-6244bcddd421" />

After commenting out all the non-compiling tests and this line, inspection in the debugger shows the data is no longer available in the response object model.

<img width="715" height="126" alt="Image" src="https://github.com/user-attachments/assets/6ca4ca7b-f4f4-45bb-bc56-96ae349ed7cf" />

Beware that our code contains extension methods like `WrapInExtendedSchema()` and `UnwrapLastExtendedSchema()`, which behave similarly to `options.UseAllOfToExtendReferenceSchemas()`, hiding most of the effects of this change. But we also use those methods for inheritance, so simply updating them to `oneOf` isn't enough to test the effects.

While changing from `allOf` with `nullable` to `oneOf` with a nested `nullable` may be allowed by the OAS spec (I haven't checked), enter the world of OpenAPI vagueness: specs that are ambiguous, docs that are incorrect, and implementations that are just odd. We started our OpenAPI project in 2021 and have found dozens of oddities and bugs in Swashbuckle, NSwag and Kiota, many of which we implemented workarounds for; others were [unsolvable](https://www.jsonapi.net/usage/openapi-client.html?tabs=nswag#known-limitations). Even if we _can_ get our code to adapt, this is still a breaking change whose consequences are impossible to oversee, because we don't know how Swashbuckle is being used by everyone. If the change is going to stay, I believe it requires a major version bump of Swashbuckle (and we'll have quite some work to do to adapt).

**Comment by martincostello** [comment]
> I assumed from the description that the OpenAPI document was causing Kiota to generate non-sensical C# to descript the API client but that's not the case.

You can ignore that - I'd written it in a draft, then found it to be incorrect later, I just forgot to delete it.

**Comment by bkoelman** [comment]
Thinking a bit more about this, the `options.UseAllOfToExtendReferenceSchemas()` method was specifically introduced to solve the problem that `nullable`, `summary`, `description` and others can't be combined directly with a reference schema. As the method's name suggests, the implementation solves this by wrapping the `$ref` in an `allOf`. Since the "fix", that no longer holds true, because `oneOf` is now sometimes used, which is pretty confusing. 

The "right" way to express `nullable` with `$ref` has been debated intensively. For reference, see the links in the description of https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/1372. A quick google for "openapi nullable ref" pointed me to https://stackoverflow.com/a/48114924, which recommends using `allOf` (which Swashbuckle always did).

**Comment by martincostello** [comment]
Fixed by #3687.

#3688 shows the test failures that catch the issue if the change is re-applied.

```text
Error: /home/runner/work/Swashbuckle.AspNetCore/Swashbuckle.AspNetCore/test/Swashbuckle.AspNetCore.IntegrationTests/CodeGenerationTests.cs(146,26): error CS1503: Argument 1: cannot convert from 'TodoApp.Client.Models.TodoPriority' to 'System.DateTime' [/home/runner/work/Swashbuckle.AspNetCore/Swashbuckle.AspNetCore/test/Swashbuckle.AspNetCore.IntegrationTests/Swashbuckle.AspNetCore.IntegrationTests.csproj::TargetFramework=net10.0]
Error: /home/runner/work/Swashbuckle.AspNetCore/Swashbuckle.AspNetCore/test/Swashbuckle.AspNetCore.IntegrationTests/CodeGenerationTests.cs(146,45): error CS1503: Argument 2: cannot convert from 'TodoApp.Client.Models.TodoItemModel.TodoItemModel_priority' to 'System.DateTime' [/home/runner/work/Swashbuckle.AspNetCore/Swashbuckle.AspNetCore/test/Swashbuckle.AspNetCore.IntegrationTests/Swashbuckle.AspNetCore.IntegrationTests.csproj::TargetFramework=net10.0]
```

> Looks the bug here is triggering a bug in Kiota, which is why the compilation is initially failing. Assuming I've understood things correctly, Kiota is emitting code for IBackedModel when "usesBackingStore": true, but isn't emitting the using Microsoft.Kiota.Abstractions.Store; to go with it.

This should be logged with the Kiota project, as regardless of the bug here, it shouldn't be emitting code that doesn't compile in isolation from any other code that would then depend on it (i.e. your tests).

**Comment by bkoelman** [comment]
That PR doesn't fix the problem at all. It removes nullability entirely, which is just wrong.

<img width="1116" height="349" alt="Image" src="https://github.com/user-attachments/assets/c9c46312-5c24-490e-8fd0-94ee7d847966" />

> This should be logged with the Kiota project, as regardless of the bug here, it shouldn't be emitting code that doesn't compile in isolation from any other code that would then depend on it (i.e. your tests).

Kiota is full of bugs. Introducing a break here and then, telling another project it needs to update is not a solution.

**Comment by martincostello** [comment]
From the PR description:

> This also identified, via the use of https://apinotes.io/openapi-validator, that nullable shouldn't be emitted for OpenAPI 3.0 if type isn't, so that has also been resolved. Unfortunately I haven't yet found a validator that flags that that can be used in CI.

Is this correct, or is their validator wrong (it was the only validator I could find that didn't like it)?

This change (141a54c0a4920d74c67b457f7015e64ac8ee0a30) was made solely due to seeing the validate error in the schema after I reverted the original change (46073c67e4d834cbacefe98c96e358dee3f116f7). It was unrelated to anything to do with Kiota.

With 141a54c0a4920d74c67b457f7015e64ac8ee0a30 [this file](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/141a54c0a4920d74c67b457f7015e64ac8ee0a30/test/Swashbuckle.AspNetCore.IntegrationTests/snapshots/VerifyTests.Swagger_IsValidJson_No_Startup_entryPointType%3DTodoApp.Program_swaggerRequestUri%3Dv1.DotNet10_0.verified.txt):

<img width="1794" height="251" alt="Image" src="https://github.com/user-attachments/assets/bcf9ea1c-9a62-4676-b15e-0b36b894251c" />

With 46073c67e4d834cbacefe98c96e358dee3f116f7 [this file](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/46073c67e4d834cbacefe98c96e358dee3f116f7/test/Swashbuckle.AspNetCore.IntegrationTests/snapshots/VerifyTests.Swagger_IsValidJson_No_Startup_entryPointType%3DTodoApp.Program_swaggerRequestUri%3Dv1.DotNet10_0.verified.txt):

<img width="1782" height="633" alt="Image" src="https://github.com/user-attachments/assets/4c8cfd4f-7101-478c-8c31-ec937aefc927" />

Possibilities:

1. The validator is right - the generated schema was wrong, now it's fixed, but that means nullability isn't correctly represented (a new bug, or possibly a flaw in the original solution to try to get it to work)
2. The validator is right - the generated schema was wrong, but the change should be reverted because it breaks people, so it's left as a known-wrong
3. It's wrong, the generated schema was correct, so the change from 141a54c0a4920d74c67b457f7015e64ac8ee0a30 should be reverted
4. Some other possibility I've not thought of?

**Comment by bkoelman** [comment]
4: the spec is wrong. It was added in a 3x patch release of the spec to satisfy validators for JSON Schema, but the impact on code generators wasn't considered. See https://github.com/microsoft/OpenAPI.NET/issues/2342#issuecomment-2886543904.

**Comment by bkoelman** [comment]
Can you bump the patch version in dev builds? Because now our version wildcard doesn't work anymore. Any new pushes here result in a version that's lower than the almost-released stable one.

And can you reopen this issue? I don't have permission.

**Comment by martincostello** [comment]
The next release is still currently planned to be 10.0.2 though - 10.0.2 effectively never happened since I deleted it and the tag and it never made it to NuGet.

I would delete the package from MyGet, but I don't have the access to unfortunately.

At this point there's no functional changes for 10.0.2 in the default branch either, it's all just test changes now things have been reverted.

**Comment by martincostello** [comment]
> I would delete the package from MyGet, but I don't have the access to unfortunately.

I'll see if `nuget delete` will work tomorrow against MyGet: https://learn.microsoft.com/nuget/reference/cli-reference/cli-ref-delete

**Comment by bkoelman** [comment]
The following works for the moment:
```xml
<SwashbuckleVersion>[10.0.*-*,10.0.2)</SwashbuckleVersion>
```

<img width="312" height="20" alt="Image" src="https://github.com/user-attachments/assets/aedd6a7a-d3c4-44b1-9a61-003a67e3ebb7" />

All tests are green again with that version. Thanks for addressing this.

**Comment by martincostello** [comment]
The 10.0.2 packages should all be gone from MyGet now: [delete job](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/actions/runs/19820193293/job/56780555577).

**Comment by bkoelman** [comment]
I don't think that worked. When I restore the wildcard, it still resolves to 10.0.2, even after running `git clean -xdff` and `dotnet nuget locals --clear all`. At https://www.myget.org/F/domaindrivendev/Packages, I still see references to that version.

**Comment by bkoelman** [comment]
I'm using the following `nuget.config`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="SwashbuckleMyGet" value="https://www.myget.org/F/domaindrivendev/api/v3/index.json" />
  </packageSources>
  <packageSourceMapping>
    <packageSource key="nuget.org">
      <package pattern="*" />
    </packageSource>
    <packageSource key="SwashbuckleMyGet">
      <package pattern="Swashbuckle.*" />
    </packageSource>
  </packageSourceMapping>
</configuration>
```

**Comment by martincostello** [comment]
I don't know why MyGet didn't delete the packages despite `dotnet nuget delete` reporting success.

I don't have any access to the UI in the feed to be able to try manually deleting them.

**Comment by bkoelman** [comment]
It's fine, we'll revert to the original wildcard once possible. This is not blocking anymore.
